#server:
#   port: 8088
#   context-path: /cmsweb

spring:
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
    devtools:
      restart:
        enabled: true

    jmx:
      enabled: false

    mvc:
      view:
        prefix: /WEB-INF/views/
        suffix: .jsp