package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.DbCompany;

public interface DbCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_company
     *
     * @mbggenerated Fri Apr 24 17:58:40 CST 2020
     */
    int deleteByPrimaryKey(String companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_company
     *
     * @mbggenerated Fri Apr 24 17:58:40 CST 2020
     */
    int insert(DbCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_company
     *
     * @mbggenerated Fri Apr 24 17:58:40 CST 2020
     */
    int insertSelective(DbCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_company
     *
     * @mbggenerated Fri Apr 24 17:58:40 CST 2020
     */
    DbCompany selectByPrimaryKey(String companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_company
     *
     * @mbggenerated Fri Apr 24 17:58:40 CST 2020
     */
    int updateByPrimaryKeySelective(DbCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_company
     *
     * @mbggenerated Fri Apr 24 17:58:40 CST 2020
     */
    int updateByPrimaryKey(DbCompany record);
}