package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.DbDepartment;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DbDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_department
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    int deleteByPrimaryKey(String departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_department
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    int insert(DbDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_department
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    int insertSelective(DbDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_department
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    DbDepartment selectByPrimaryKey(String departmentId);

    /**
     * 查询有效的员工信息
     * @param departmentId
     * @return
     */
    DbDepartment selectByPrimaryKeyByStatus(String departmentId);
    /**
     * 根据公司Id查询部门列表
     * @param companyId
     * @return
     */
    List<DbDepartment> selectByPrimaryKeyList(@Param("companyId") String companyId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_department
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    int updateByPrimaryKeySelective(DbDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_department
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    int updateByPrimaryKey(DbDepartment record);




    /**
     * 查询部门总记录数
     * @return
     */
    Long selectDepartmentCount(DbDepartment department);

    /**
     * 部门信息分页展示
     * @return
     */
    List<DbDepartment> selectDepartmentListByPage(DbDepartment department);


    /**
     * 验证部门名称唯一性
     * @return
     */
    Long selectDepartmentNameCheck(@Param("departmentName") String departmentName, @Param("departmentId") String departmentId);
}