package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.DbDemandManager;

import java.util.List;

public interface DbDemandManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_demand_manager
     *
     * @mbggenerated Thu May 21 23:51:45 CST 2020
     */
    int deleteByPrimaryKey(String demandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_demand_manager
     *
     * @mbggenerated Thu May 21 23:51:45 CST 2020
     */
    int insert(DbDemandManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_demand_manager
     *
     * @mbggenerated Thu May 21 23:51:45 CST 2020
     */
    int insertSelective(DbDemandManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_demand_manager
     *
     * @mbggenerated Thu May 21 23:51:45 CST 2020
     */
    DbDemandManager selectByPrimaryKey(String demandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_demand_manager
     *
     * @mbggenerated Thu May 21 23:51:45 CST 2020
     */
    int updateByPrimaryKeySelective(DbDemandManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_demand_manager
     *
     * @mbggenerated Thu May 21 23:51:45 CST 2020
     */
    int updateByPrimaryKey(DbDemandManager record);


    /**
     * 查询需求总记录数
     * @return
     */
    Long selectDemandManagerCount(DbDemandManager demandManager);

    /**
     * 需求信息分页展示
     * @return
     */
    List<DbDemandManager> selectDemandManagerListByPage(DbDemandManager demandManager);


}