package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.DbDepartment;

public interface DbDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_department
     *
     * @mbggenerated Sun Apr 26 00:00:58 CST 2020
     */
    int deleteByPrimaryKey(String departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_department
     *
     * @mbggenerated Sun Apr 26 00:00:58 CST 2020
     */
    int insert(DbDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_department
     *
     * @mbggenerated Sun Apr 26 00:00:58 CST 2020
     */
    int insertSelective(DbDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_department
     *
     * @mbggenerated Sun Apr 26 00:00:58 CST 2020
     */
    DbDepartment selectByPrimaryKey(String departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_department
     *
     * @mbggenerated Sun Apr 26 00:00:58 CST 2020
     */
    int updateByPrimaryKeySelective(DbDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_department
     *
     * @mbggenerated Sun Apr 26 00:00:58 CST 2020
     */
    int updateByPrimaryKey(DbDepartment record);
}