package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.DbEmployee;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DbEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_employee
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    int deleteByPrimaryKey(String employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_employee
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    int insert(DbEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_employee
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    int insertSelective(DbEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_employee
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    DbEmployee selectByPrimaryKey(String employeeId);

    DbEmployee selectByPrimaryKeyByStatus(String employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_employee
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    int updateByPrimaryKeySelective(DbEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_employee
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    int updateByPrimaryKey(DbEmployee record);



    /**
     * 查询员工总记录数
     * @return
     */
    Long selectEmployeeCount(DbEmployee employee);

    /**
     * 员工信息分页展示
     * @return
     */
    List<DbEmployee> selectEmployeeListByPage(DbEmployee employee);


    /**
     * 根据项目Id查询员工信息
     * @param projectId
     * @return
     */
    List<DbEmployee>selectEmployeeListByProjectId(@Param("projectId") String projectId,@Param("memberId") String memberId);

}