package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.DbMemberManager;

public interface DbMemberManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_member_manager
     *
     * @mbggenerated Wed May 06 18:04:32 CST 2020
     */
    int deleteByPrimaryKey(String memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_member_manager
     *
     * @mbggenerated Wed May 06 18:04:32 CST 2020
     */
    int insert(DbMemberManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_member_manager
     *
     * @mbggenerated Wed May 06 18:04:32 CST 2020
     */
    int insertSelective(DbMemberManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_member_manager
     *
     * @mbggenerated Wed May 06 18:04:32 CST 2020
     */
    DbMemberManager selectByPrimaryKey(String memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_member_manager
     *
     * @mbggenerated Wed May 06 18:04:32 CST 2020
     */
    int updateByPrimaryKeySelective(DbMemberManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_member_manager
     *
     * @mbggenerated Wed May 06 18:04:32 CST 2020
     */
    int updateByPrimaryKey(DbMemberManager record);
}