package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.DbProject;

import java.util.List;

public interface DbProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_project
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    int deleteByPrimaryKey(String projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_project
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    int insert(DbProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_project
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    int insertSelective(DbProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_project
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    DbProject selectByPrimaryKey(String projectId);

    DbProject selectByPrimaryKeyByStatus(String projectId);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_project
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    int updateByPrimaryKeySelective(DbProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_project
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    int updateByPrimaryKey(DbProject record);


    /**
     * 查询项目总记录数
     * @return
     */
    Long selectProjectCount(DbProject project);

    /**
     * 项目信息分页展示
     * @return
     */
    List<DbProject> selectProjectListByPage(DbProject project);

    /**
     * 有效的项目列表信息
     * @return
     */
    List<DbProject> selectProjectList();

}