package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.DbProject;

public interface DbProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_project
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    int deleteByPrimaryKey(String projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_project
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    int insert(DbProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_project
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    int insertSelective(DbProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_project
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    DbProject selectByPrimaryKey(String projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_project
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    int updateByPrimaryKeySelective(DbProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_project
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    int updateByPrimaryKey(DbProject record);
}