package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.DbRole;

import java.util.List;

public interface DbRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    int insert(DbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    int insertSelective(DbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    DbRole selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    int updateByPrimaryKeySelective(DbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    int updateByPrimaryKey(DbRole record);

    /**
     * 查询角色总记录数
     * @param role
     * @return
     */
    Long selectRoleCount(DbRole role);

    /**
     * 角色信息分页展示
     * @param role
     * @return
     */
    List<DbRole> selectRoleListByPage(DbRole role);

}