package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.DbRoleMenu;

public interface DbRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role_menu
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int deleteByPrimaryKey(String roleMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role_menu
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int insert(DbRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role_menu
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int insertSelective(DbRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role_menu
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    DbRoleMenu selectByPrimaryKey(String roleMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role_menu
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int updateByPrimaryKeySelective(DbRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role_menu
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int updateByPrimaryKey(DbRoleMenu record);
}