package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.DbRole;

public interface DbRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int insert(DbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int insertSelective(DbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    DbRole selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int updateByPrimaryKeySelective(DbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int updateByPrimaryKey(DbRole record);
}