package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.DbRole;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DbRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    int insert(DbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    int insertSelective(DbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    DbRole selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    int updateByPrimaryKeySelective(DbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_role
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    int updateByPrimaryKey(DbRole record);

    /**
     * 查询角色总记录数
     * @param role
     * @return
     */
    Long selectRoleCount(DbRole role);

    /**
     * 角色信息分页展示
     * @param role
     * @return
     */
    List<DbRole> selectRoleListByPage(DbRole role);

    /**
     * 验证角色名称唯一性
     * @param roleName 角色名称
     * @param roleId   角色Id
     * @return
     */
    Long selectRoleNameCheck(@Param("roleName") String roleName, @Param("roleId") String roleId);


    /**
     * 查询角色最大排序
     * @return
     */
    Integer selectRoleMaxOrderNo();



    /**
     * 查询角色Id
     * @param roleType   角色类型
     * @return
     */
    String selectRoleId(@Param("roleType") String roleType);



}