package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.DbSysLog;

public interface DbSysLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_sys_log
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int deleteByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_sys_log
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int insert(DbSysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_sys_log
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int insertSelective(DbSysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_sys_log
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    DbSysLog selectByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_sys_log
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int updateByPrimaryKeySelective(DbSysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_sys_log
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int updateByPrimaryKey(DbSysLog record);
}