package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.DbTaskMember;

public interface DbTaskMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_task_member
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    int deleteByPrimaryKey(String taskMemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_task_member
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    int insert(DbTaskMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_task_member
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    int insertSelective(DbTaskMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_task_member
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    DbTaskMember selectByPrimaryKey(String taskMemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_task_member
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    int updateByPrimaryKeySelective(DbTaskMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_task_member
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    int updateByPrimaryKey(DbTaskMember record);
}