package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.DbUser;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DbUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int insert(DbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int insertSelective(DbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    DbUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int updateByPrimaryKeySelective(DbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int updateByPrimaryKey(DbUser record);


    /**
     * 根据登录用户名和状态查询用户信息
     * @param userAccount 用户账号
     * @param userStatus  用户状态
     * @return
     */
    DbUser selectUserByUserAccountAndStatus(@Param("userAccount") String userAccount, @Param("userStatus") Integer userStatus);


    /**
     * 查询用户总记录数
     * @param user 用户对象
     * @return
     */
    Long selectUserCount (DbUser user);

    /**
     * 用户信息分页展示
     * @param user
     * @return
     */
    List<DbUser> selectUserListByPage(DbUser user);





}