package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.DbUser;

public interface DbUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int insert(DbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int insertSelective(DbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    DbUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int updateByPrimaryKeySelective(DbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int updateByPrimaryKey(DbUser record);
}