package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.DbUserRole;
import org.apache.ibatis.annotations.Param;

public interface DbUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user_role
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int deleteByPrimaryKey(String userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user_role
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int insert(DbUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user_role
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int insertSelective(DbUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user_role
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    DbUserRole selectByPrimaryKey(String userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user_role
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int updateByPrimaryKeySelective(DbUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user_role
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    int updateByPrimaryKey(DbUserRole record);

    /**
     * 根据用户Id,查询用户角色信息
     * @param userId 用户Id
     * @return
     */
    DbUserRole selectUserRolesByUserId(@Param("userId") String userId);
}