package com.yxb.cms.domain.vo;

import com.yxb.cms.domain.dto.PageDto;

import java.io.Serializable;
import java.util.Date;

public class DbDepartment extends PageDto implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_department.department_id
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    private String departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_department.department_name
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_department.established_time
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    private String establishedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_department.department_principal
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    private String departmentPrincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_department.department_principal_tel
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    private String departmentPrincipalTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_department.company_id
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_department.company_name
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_department.department_status
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    private Integer departmentStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_department.creater_user_id
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    private String createrUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_department.creater_time
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    private Date createrTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_department.modifier_user_id
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    private String modifierUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_department.modifier_time
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    private Date modifierTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_department.department_id
     *
     * @return the value of db_department.department_id
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_department.department_id
     *
     * @param departmentId the value for db_department.department_id
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_department.department_name
     *
     * @return the value of db_department.department_name
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_department.department_name
     *
     * @param departmentName the value for db_department.department_name
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_department.established_time
     *
     * @return the value of db_department.established_time
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public String getEstablishedTime() {
        return establishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_department.established_time
     *
     * @param establishedTime the value for db_department.established_time
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public void setEstablishedTime(String establishedTime) {
        this.establishedTime = establishedTime == null ? null : establishedTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_department.department_principal
     *
     * @return the value of db_department.department_principal
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public String getDepartmentPrincipal() {
        return departmentPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_department.department_principal
     *
     * @param departmentPrincipal the value for db_department.department_principal
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public void setDepartmentPrincipal(String departmentPrincipal) {
        this.departmentPrincipal = departmentPrincipal == null ? null : departmentPrincipal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_department.department_principal_tel
     *
     * @return the value of db_department.department_principal_tel
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public String getDepartmentPrincipalTel() {
        return departmentPrincipalTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_department.department_principal_tel
     *
     * @param departmentPrincipalTel the value for db_department.department_principal_tel
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public void setDepartmentPrincipalTel(String departmentPrincipalTel) {
        this.departmentPrincipalTel = departmentPrincipalTel == null ? null : departmentPrincipalTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_department.company_id
     *
     * @return the value of db_department.company_id
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_department.company_id
     *
     * @param companyId the value for db_department.company_id
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_department.company_name
     *
     * @return the value of db_department.company_name
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_department.company_name
     *
     * @param companyName the value for db_department.company_name
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_department.department_status
     *
     * @return the value of db_department.department_status
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public Integer getDepartmentStatus() {
        return departmentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_department.department_status
     *
     * @param departmentStatus the value for db_department.department_status
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public void setDepartmentStatus(Integer departmentStatus) {
        this.departmentStatus = departmentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_department.creater_user_id
     *
     * @return the value of db_department.creater_user_id
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public String getCreaterUserId() {
        return createrUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_department.creater_user_id
     *
     * @param createrUserId the value for db_department.creater_user_id
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public void setCreaterUserId(String createrUserId) {
        this.createrUserId = createrUserId == null ? null : createrUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_department.creater_time
     *
     * @return the value of db_department.creater_time
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public Date getCreaterTime() {
        return createrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_department.creater_time
     *
     * @param createrTime the value for db_department.creater_time
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public void setCreaterTime(Date createrTime) {
        this.createrTime = createrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_department.modifier_user_id
     *
     * @return the value of db_department.modifier_user_id
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public String getModifierUserId() {
        return modifierUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_department.modifier_user_id
     *
     * @param modifierUserId the value for db_department.modifier_user_id
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public void setModifierUserId(String modifierUserId) {
        this.modifierUserId = modifierUserId == null ? null : modifierUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_department.modifier_time
     *
     * @return the value of db_department.modifier_time
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public Date getModifierTime() {
        return modifierTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_department.modifier_time
     *
     * @param modifierTime the value for db_department.modifier_time
     *
     * @mbggenerated Sun Apr 26 09:04:27 CST 2020
     */
    public void setModifierTime(Date modifierTime) {
        this.modifierTime = modifierTime;
    }
}