package com.yxb.cms.domain.vo;

import com.yxb.cms.domain.dto.PageDto;

import java.io.Serializable;
import java.util.Date;

public class DbDemandManager extends PageDto implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_demand_manager.demand_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private String demandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_demand_manager.demand_name
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private String demandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_demand_manager.demand_desc
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private String demandDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_demand_manager.demand_type
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private Integer demandType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_demand_manager.priority
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_demand_manager.demand_status
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private Integer demandStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_demand_manager.start_time
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_demand_manager.plan_finish_time
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private String planFinishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_demand_manager.finish_time
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private String finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_demand_manager.finish_rate
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private Double finishRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_demand_manager.overdue_num
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private Double overdueNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_demand_manager.remaining_days
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private Double remainingDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_demand_manager.release_time
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private String releaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_demand_manager.project_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_demand_manager.project_name
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_demand_manager.creater_user_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private String createrUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_demand_manager.creater_time
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private Date createrTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_demand_manager.modifier_user_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private String modifierUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_demand_manager.modifier_time
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private Date modifierTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_demand_manager.demand_id
     *
     * @return the value of db_demand_manager.demand_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public String getDemandId() {
        return demandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_demand_manager.demand_id
     *
     * @param demandId the value for db_demand_manager.demand_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setDemandId(String demandId) {
        this.demandId = demandId == null ? null : demandId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_demand_manager.demand_name
     *
     * @return the value of db_demand_manager.demand_name
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public String getDemandName() {
        return demandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_demand_manager.demand_name
     *
     * @param demandName the value for db_demand_manager.demand_name
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setDemandName(String demandName) {
        this.demandName = demandName == null ? null : demandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_demand_manager.demand_desc
     *
     * @return the value of db_demand_manager.demand_desc
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public String getDemandDesc() {
        return demandDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_demand_manager.demand_desc
     *
     * @param demandDesc the value for db_demand_manager.demand_desc
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setDemandDesc(String demandDesc) {
        this.demandDesc = demandDesc == null ? null : demandDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_demand_manager.demand_type
     *
     * @return the value of db_demand_manager.demand_type
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public Integer getDemandType() {
        return demandType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_demand_manager.demand_type
     *
     * @param demandType the value for db_demand_manager.demand_type
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setDemandType(Integer demandType) {
        this.demandType = demandType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_demand_manager.priority
     *
     * @return the value of db_demand_manager.priority
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_demand_manager.priority
     *
     * @param priority the value for db_demand_manager.priority
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_demand_manager.demand_status
     *
     * @return the value of db_demand_manager.demand_status
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public Integer getDemandStatus() {
        return demandStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_demand_manager.demand_status
     *
     * @param demandStatus the value for db_demand_manager.demand_status
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setDemandStatus(Integer demandStatus) {
        this.demandStatus = demandStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_demand_manager.start_time
     *
     * @return the value of db_demand_manager.start_time
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_demand_manager.start_time
     *
     * @param startTime the value for db_demand_manager.start_time
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_demand_manager.plan_finish_time
     *
     * @return the value of db_demand_manager.plan_finish_time
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public String getPlanFinishTime() {
        return planFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_demand_manager.plan_finish_time
     *
     * @param planFinishTime the value for db_demand_manager.plan_finish_time
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setPlanFinishTime(String planFinishTime) {
        this.planFinishTime = planFinishTime == null ? null : planFinishTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_demand_manager.finish_time
     *
     * @return the value of db_demand_manager.finish_time
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public String getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_demand_manager.finish_time
     *
     * @param finishTime the value for db_demand_manager.finish_time
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setFinishTime(String finishTime) {
        this.finishTime = finishTime == null ? null : finishTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_demand_manager.finish_rate
     *
     * @return the value of db_demand_manager.finish_rate
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public Double getFinishRate() {
        return finishRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_demand_manager.finish_rate
     *
     * @param finishRate the value for db_demand_manager.finish_rate
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setFinishRate(Double finishRate) {
        this.finishRate = finishRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_demand_manager.overdue_num
     *
     * @return the value of db_demand_manager.overdue_num
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public Double getOverdueNum() {
        return overdueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_demand_manager.overdue_num
     *
     * @param overdueNum the value for db_demand_manager.overdue_num
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setOverdueNum(Double overdueNum) {
        this.overdueNum = overdueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_demand_manager.remaining_days
     *
     * @return the value of db_demand_manager.remaining_days
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public Double getRemainingDays() {
        return remainingDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_demand_manager.remaining_days
     *
     * @param remainingDays the value for db_demand_manager.remaining_days
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setRemainingDays(Double remainingDays) {
        this.remainingDays = remainingDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_demand_manager.release_time
     *
     * @return the value of db_demand_manager.release_time
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public String getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_demand_manager.release_time
     *
     * @param releaseTime the value for db_demand_manager.release_time
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setReleaseTime(String releaseTime) {
        this.releaseTime = releaseTime == null ? null : releaseTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_demand_manager.project_id
     *
     * @return the value of db_demand_manager.project_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_demand_manager.project_id
     *
     * @param projectId the value for db_demand_manager.project_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_demand_manager.project_name
     *
     * @return the value of db_demand_manager.project_name
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_demand_manager.project_name
     *
     * @param projectName the value for db_demand_manager.project_name
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_demand_manager.creater_user_id
     *
     * @return the value of db_demand_manager.creater_user_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public String getCreaterUserId() {
        return createrUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_demand_manager.creater_user_id
     *
     * @param createrUserId the value for db_demand_manager.creater_user_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setCreaterUserId(String createrUserId) {
        this.createrUserId = createrUserId == null ? null : createrUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_demand_manager.creater_time
     *
     * @return the value of db_demand_manager.creater_time
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public Date getCreaterTime() {
        return createrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_demand_manager.creater_time
     *
     * @param createrTime the value for db_demand_manager.creater_time
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setCreaterTime(Date createrTime) {
        this.createrTime = createrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_demand_manager.modifier_user_id
     *
     * @return the value of db_demand_manager.modifier_user_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public String getModifierUserId() {
        return modifierUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_demand_manager.modifier_user_id
     *
     * @param modifierUserId the value for db_demand_manager.modifier_user_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setModifierUserId(String modifierUserId) {
        this.modifierUserId = modifierUserId == null ? null : modifierUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_demand_manager.modifier_time
     *
     * @return the value of db_demand_manager.modifier_time
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public Date getModifierTime() {
        return modifierTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_demand_manager.modifier_time
     *
     * @param modifierTime the value for db_demand_manager.modifier_time
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setModifierTime(Date modifierTime) {
        this.modifierTime = modifierTime;
    }
}