package com.yxb.cms.domain.vo;

import com.yxb.cms.domain.dto.PageDto;

import java.io.Serializable;
import java.util.Date;

public class DbEmployee extends PageDto implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_employee.employee_id
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    private String employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_employee.employee_name
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    private String employeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_employee.employee_position
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    private Integer employeePosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_employee.employee_tel
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    private String employeeTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_employee.employee_sex
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    private Integer employeeSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_employee.employee_age
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    private Integer employeeAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_employee.employee_birthday
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    private String employeeBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_employee.employee_qq
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    private String employeeQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_employee.employee_weixin
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    private String employeeWeixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_employee.company_id
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_employee.company_name
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_employee.department_id
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    private String departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_employee.department_name
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_employee.employee_address
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    private String employeeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_employee.employee_status
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    private Integer employeeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_employee.creater_user_id
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    private String createrUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_employee.creater_time
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    private Date createrTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_employee.modifier_user_id
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    private String modifierUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_employee.modifier_time
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    private Date modifierTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_employee.employee_id
     *
     * @return the value of db_employee.employee_id
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_employee.employee_id
     *
     * @param employeeId the value for db_employee.employee_id
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_employee.employee_name
     *
     * @return the value of db_employee.employee_name
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_employee.employee_name
     *
     * @param employeeName the value for db_employee.employee_name
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_employee.employee_position
     *
     * @return the value of db_employee.employee_position
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public Integer getEmployeePosition() {
        return employeePosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_employee.employee_position
     *
     * @param employeePosition the value for db_employee.employee_position
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public void setEmployeePosition(Integer employeePosition) {
        this.employeePosition = employeePosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_employee.employee_tel
     *
     * @return the value of db_employee.employee_tel
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public String getEmployeeTel() {
        return employeeTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_employee.employee_tel
     *
     * @param employeeTel the value for db_employee.employee_tel
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public void setEmployeeTel(String employeeTel) {
        this.employeeTel = employeeTel == null ? null : employeeTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_employee.employee_sex
     *
     * @return the value of db_employee.employee_sex
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public Integer getEmployeeSex() {
        return employeeSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_employee.employee_sex
     *
     * @param employeeSex the value for db_employee.employee_sex
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public void setEmployeeSex(Integer employeeSex) {
        this.employeeSex = employeeSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_employee.employee_age
     *
     * @return the value of db_employee.employee_age
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public Integer getEmployeeAge() {
        return employeeAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_employee.employee_age
     *
     * @param employeeAge the value for db_employee.employee_age
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public void setEmployeeAge(Integer employeeAge) {
        this.employeeAge = employeeAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_employee.employee_birthday
     *
     * @return the value of db_employee.employee_birthday
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public String getEmployeeBirthday() {
        return employeeBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_employee.employee_birthday
     *
     * @param employeeBirthday the value for db_employee.employee_birthday
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public void setEmployeeBirthday(String employeeBirthday) {
        this.employeeBirthday = employeeBirthday == null ? null : employeeBirthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_employee.employee_qq
     *
     * @return the value of db_employee.employee_qq
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public String getEmployeeQq() {
        return employeeQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_employee.employee_qq
     *
     * @param employeeQq the value for db_employee.employee_qq
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public void setEmployeeQq(String employeeQq) {
        this.employeeQq = employeeQq == null ? null : employeeQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_employee.employee_weixin
     *
     * @return the value of db_employee.employee_weixin
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public String getEmployeeWeixin() {
        return employeeWeixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_employee.employee_weixin
     *
     * @param employeeWeixin the value for db_employee.employee_weixin
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public void setEmployeeWeixin(String employeeWeixin) {
        this.employeeWeixin = employeeWeixin == null ? null : employeeWeixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_employee.company_id
     *
     * @return the value of db_employee.company_id
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_employee.company_id
     *
     * @param companyId the value for db_employee.company_id
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_employee.company_name
     *
     * @return the value of db_employee.company_name
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_employee.company_name
     *
     * @param companyName the value for db_employee.company_name
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_employee.department_id
     *
     * @return the value of db_employee.department_id
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_employee.department_id
     *
     * @param departmentId the value for db_employee.department_id
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_employee.department_name
     *
     * @return the value of db_employee.department_name
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_employee.department_name
     *
     * @param departmentName the value for db_employee.department_name
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_employee.employee_address
     *
     * @return the value of db_employee.employee_address
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public String getEmployeeAddress() {
        return employeeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_employee.employee_address
     *
     * @param employeeAddress the value for db_employee.employee_address
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public void setEmployeeAddress(String employeeAddress) {
        this.employeeAddress = employeeAddress == null ? null : employeeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_employee.employee_status
     *
     * @return the value of db_employee.employee_status
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public Integer getEmployeeStatus() {
        return employeeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_employee.employee_status
     *
     * @param employeeStatus the value for db_employee.employee_status
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public void setEmployeeStatus(Integer employeeStatus) {
        this.employeeStatus = employeeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_employee.creater_user_id
     *
     * @return the value of db_employee.creater_user_id
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public String getCreaterUserId() {
        return createrUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_employee.creater_user_id
     *
     * @param createrUserId the value for db_employee.creater_user_id
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public void setCreaterUserId(String createrUserId) {
        this.createrUserId = createrUserId == null ? null : createrUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_employee.creater_time
     *
     * @return the value of db_employee.creater_time
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public Date getCreaterTime() {
        return createrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_employee.creater_time
     *
     * @param createrTime the value for db_employee.creater_time
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public void setCreaterTime(Date createrTime) {
        this.createrTime = createrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_employee.modifier_user_id
     *
     * @return the value of db_employee.modifier_user_id
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public String getModifierUserId() {
        return modifierUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_employee.modifier_user_id
     *
     * @param modifierUserId the value for db_employee.modifier_user_id
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public void setModifierUserId(String modifierUserId) {
        this.modifierUserId = modifierUserId == null ? null : modifierUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_employee.modifier_time
     *
     * @return the value of db_employee.modifier_time
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public Date getModifierTime() {
        return modifierTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_employee.modifier_time
     *
     * @param modifierTime the value for db_employee.modifier_time
     *
     * @mbggenerated Sun Apr 26 14:58:23 CST 2020
     */
    public void setModifierTime(Date modifierTime) {
        this.modifierTime = modifierTime;
    }


    public String getEmployeePositionLable(){
        if(this.getEmployeePosition() != null){
            if(this.getEmployeePosition() == 1){
                return "总经理";
            }else if(this.getEmployeePosition() == 2) {
                return "副总经理";
            }else if(this.getEmployeePosition() == 3) {
                return "部门经理";
            }else if(this.getEmployeePosition() == 4) {
                return "职员";
            }else {
                return "";
            }
        }else{
            return "";
        }

    }


    public String getEmployeeSexLable(){
        if(this.getEmployeeSex() != null){
            if(this.getEmployeeSex() == 1){
                return "男";
            }else if(this.getEmployeeSex() == 2) {
                return "女";
            }else {
                return "";
            }
        }else{
            return "";
        }

    }


}