package com.yxb.cms.domain.vo;

public class DbMenuInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_menu_info.menu_info_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String menuInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_menu_info.menu_parent_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String menuParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_menu_info.menu_name
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_menu_info.menu_type
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private Integer menuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_menu_info.menu_code
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String menuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_menu_info.menu_status
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private Integer menuStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_menu_info.menu_level
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private Integer menuLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_menu_info.menu_link_address
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String menuLinkAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_menu_info.menu_image
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String menuImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_menu_info.menu_order_no
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private Integer menuOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_menu_info.menu_desc
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String menuDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_menu_info.menu_info_id
     *
     * @return the value of db_menu_info.menu_info_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getMenuInfoId() {
        return menuInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_menu_info.menu_info_id
     *
     * @param menuInfoId the value for db_menu_info.menu_info_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setMenuInfoId(String menuInfoId) {
        this.menuInfoId = menuInfoId == null ? null : menuInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_menu_info.menu_parent_id
     *
     * @return the value of db_menu_info.menu_parent_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getMenuParentId() {
        return menuParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_menu_info.menu_parent_id
     *
     * @param menuParentId the value for db_menu_info.menu_parent_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setMenuParentId(String menuParentId) {
        this.menuParentId = menuParentId == null ? null : menuParentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_menu_info.menu_name
     *
     * @return the value of db_menu_info.menu_name
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_menu_info.menu_name
     *
     * @param menuName the value for db_menu_info.menu_name
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_menu_info.menu_type
     *
     * @return the value of db_menu_info.menu_type
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public Integer getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_menu_info.menu_type
     *
     * @param menuType the value for db_menu_info.menu_type
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setMenuType(Integer menuType) {
        this.menuType = menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_menu_info.menu_code
     *
     * @return the value of db_menu_info.menu_code
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_menu_info.menu_code
     *
     * @param menuCode the value for db_menu_info.menu_code
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode == null ? null : menuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_menu_info.menu_status
     *
     * @return the value of db_menu_info.menu_status
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public Integer getMenuStatus() {
        return menuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_menu_info.menu_status
     *
     * @param menuStatus the value for db_menu_info.menu_status
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setMenuStatus(Integer menuStatus) {
        this.menuStatus = menuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_menu_info.menu_level
     *
     * @return the value of db_menu_info.menu_level
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public Integer getMenuLevel() {
        return menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_menu_info.menu_level
     *
     * @param menuLevel the value for db_menu_info.menu_level
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setMenuLevel(Integer menuLevel) {
        this.menuLevel = menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_menu_info.menu_link_address
     *
     * @return the value of db_menu_info.menu_link_address
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getMenuLinkAddress() {
        return menuLinkAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_menu_info.menu_link_address
     *
     * @param menuLinkAddress the value for db_menu_info.menu_link_address
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setMenuLinkAddress(String menuLinkAddress) {
        this.menuLinkAddress = menuLinkAddress == null ? null : menuLinkAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_menu_info.menu_image
     *
     * @return the value of db_menu_info.menu_image
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getMenuImage() {
        return menuImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_menu_info.menu_image
     *
     * @param menuImage the value for db_menu_info.menu_image
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setMenuImage(String menuImage) {
        this.menuImage = menuImage == null ? null : menuImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_menu_info.menu_order_no
     *
     * @return the value of db_menu_info.menu_order_no
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public Integer getMenuOrderNo() {
        return menuOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_menu_info.menu_order_no
     *
     * @param menuOrderNo the value for db_menu_info.menu_order_no
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setMenuOrderNo(Integer menuOrderNo) {
        this.menuOrderNo = menuOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_menu_info.menu_desc
     *
     * @return the value of db_menu_info.menu_desc
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getMenuDesc() {
        return menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_menu_info.menu_desc
     *
     * @param menuDesc the value for db_menu_info.menu_desc
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setMenuDesc(String menuDesc) {
        this.menuDesc = menuDesc == null ? null : menuDesc.trim();
    }
}