package com.yxb.cms.domain.vo;

import com.yxb.cms.domain.dto.PageDto;

import java.io.Serializable;
import java.util.Date;

public class DbProject extends PageDto implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_project.project_id
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_project.project_name
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_project.project_type
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    private Integer projectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_project.project_status
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    private Integer projectStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_project.approva_time
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    private String approvaTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_project.up_time
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    private String upTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_project.down_time
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    private String downTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_project.project_intro
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    private String projectIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_project.company_id
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_project.company_name
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_project.department_id
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    private String departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_project.department_name
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_project.creater_user_id
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    private String createrUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_project.creater_time
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    private Date createrTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_project.modifier_user_id
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    private String modifierUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_project.modifier_time
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    private Date modifierTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_project.project_id
     *
     * @return the value of db_project.project_id
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_project.project_id
     *
     * @param projectId the value for db_project.project_id
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_project.project_name
     *
     * @return the value of db_project.project_name
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_project.project_name
     *
     * @param projectName the value for db_project.project_name
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_project.project_type
     *
     * @return the value of db_project.project_type
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public Integer getProjectType() {
        return projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_project.project_type
     *
     * @param projectType the value for db_project.project_type
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public void setProjectType(Integer projectType) {
        this.projectType = projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_project.project_status
     *
     * @return the value of db_project.project_status
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public Integer getProjectStatus() {
        return projectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_project.project_status
     *
     * @param projectStatus the value for db_project.project_status
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public void setProjectStatus(Integer projectStatus) {
        this.projectStatus = projectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_project.approva_time
     *
     * @return the value of db_project.approva_time
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public String getApprovaTime() {
        return approvaTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_project.approva_time
     *
     * @param approvaTime the value for db_project.approva_time
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public void setApprovaTime(String approvaTime) {
        this.approvaTime = approvaTime == null ? null : approvaTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_project.up_time
     *
     * @return the value of db_project.up_time
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public String getUpTime() {
        return upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_project.up_time
     *
     * @param upTime the value for db_project.up_time
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public void setUpTime(String upTime) {
        this.upTime = upTime == null ? null : upTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_project.down_time
     *
     * @return the value of db_project.down_time
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public String getDownTime() {
        return downTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_project.down_time
     *
     * @param downTime the value for db_project.down_time
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public void setDownTime(String downTime) {
        this.downTime = downTime == null ? null : downTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_project.project_intro
     *
     * @return the value of db_project.project_intro
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public String getProjectIntro() {
        return projectIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_project.project_intro
     *
     * @param projectIntro the value for db_project.project_intro
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public void setProjectIntro(String projectIntro) {
        this.projectIntro = projectIntro == null ? null : projectIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_project.company_id
     *
     * @return the value of db_project.company_id
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_project.company_id
     *
     * @param companyId the value for db_project.company_id
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_project.company_name
     *
     * @return the value of db_project.company_name
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_project.company_name
     *
     * @param companyName the value for db_project.company_name
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_project.department_id
     *
     * @return the value of db_project.department_id
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_project.department_id
     *
     * @param departmentId the value for db_project.department_id
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_project.department_name
     *
     * @return the value of db_project.department_name
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_project.department_name
     *
     * @param departmentName the value for db_project.department_name
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_project.creater_user_id
     *
     * @return the value of db_project.creater_user_id
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public String getCreaterUserId() {
        return createrUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_project.creater_user_id
     *
     * @param createrUserId the value for db_project.creater_user_id
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public void setCreaterUserId(String createrUserId) {
        this.createrUserId = createrUserId == null ? null : createrUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_project.creater_time
     *
     * @return the value of db_project.creater_time
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public Date getCreaterTime() {
        return createrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_project.creater_time
     *
     * @param createrTime the value for db_project.creater_time
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public void setCreaterTime(Date createrTime) {
        this.createrTime = createrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_project.modifier_user_id
     *
     * @return the value of db_project.modifier_user_id
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public String getModifierUserId() {
        return modifierUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_project.modifier_user_id
     *
     * @param modifierUserId the value for db_project.modifier_user_id
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public void setModifierUserId(String modifierUserId) {
        this.modifierUserId = modifierUserId == null ? null : modifierUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_project.modifier_time
     *
     * @return the value of db_project.modifier_time
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public Date getModifierTime() {
        return modifierTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_project.modifier_time
     *
     * @param modifierTime the value for db_project.modifier_time
     *
     * @mbggenerated Wed Apr 29 11:41:26 CST 2020
     */
    public void setModifierTime(Date modifierTime) {
        this.modifierTime = modifierTime;
    }
}