package com.yxb.cms.domain.vo;

public class DbRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_role.role_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_role.role_name
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_role.role_status
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private Integer roleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_role.devolution_state
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private Integer devolutionState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_role.roles_state
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private Integer rolesState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_role.role_desc
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_role.order_no
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private Integer orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_role.role_type
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String roleType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_role.role_id
     *
     * @return the value of db_role.role_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_role.role_id
     *
     * @param roleId the value for db_role.role_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_role.role_name
     *
     * @return the value of db_role.role_name
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_role.role_name
     *
     * @param roleName the value for db_role.role_name
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_role.role_status
     *
     * @return the value of db_role.role_status
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public Integer getRoleStatus() {
        return roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_role.role_status
     *
     * @param roleStatus the value for db_role.role_status
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setRoleStatus(Integer roleStatus) {
        this.roleStatus = roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_role.devolution_state
     *
     * @return the value of db_role.devolution_state
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public Integer getDevolutionState() {
        return devolutionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_role.devolution_state
     *
     * @param devolutionState the value for db_role.devolution_state
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setDevolutionState(Integer devolutionState) {
        this.devolutionState = devolutionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_role.roles_state
     *
     * @return the value of db_role.roles_state
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public Integer getRolesState() {
        return rolesState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_role.roles_state
     *
     * @param rolesState the value for db_role.roles_state
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setRolesState(Integer rolesState) {
        this.rolesState = rolesState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_role.role_desc
     *
     * @return the value of db_role.role_desc
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_role.role_desc
     *
     * @param roleDesc the value for db_role.role_desc
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_role.order_no
     *
     * @return the value of db_role.order_no
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_role.order_no
     *
     * @param orderNo the value for db_role.order_no
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_role.role_type
     *
     * @return the value of db_role.role_type
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_role.role_type
     *
     * @param roleType the value for db_role.role_type
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }
}