package com.yxb.cms.domain.vo;

import com.yxb.cms.domain.dto.PageDto;

import java.io.Serializable;

public class DbRole extends PageDto implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_role.role_id
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_role.role_name
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_role.role_type
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    private Integer roleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_role.role_status
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    private Integer roleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_role.role_desc
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_role.order_no
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    private Integer orderNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_role.role_id
     *
     * @return the value of db_role.role_id
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_role.role_id
     *
     * @param roleId the value for db_role.role_id
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_role.role_name
     *
     * @return the value of db_role.role_name
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_role.role_name
     *
     * @param roleName the value for db_role.role_name
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_role.role_type
     *
     * @return the value of db_role.role_type
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    public Integer getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_role.role_type
     *
     * @param roleType the value for db_role.role_type
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    public void setRoleType(Integer roleType) {
        this.roleType = roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_role.role_status
     *
     * @return the value of db_role.role_status
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    public Integer getRoleStatus() {
        return roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_role.role_status
     *
     * @param roleStatus the value for db_role.role_status
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    public void setRoleStatus(Integer roleStatus) {
        this.roleStatus = roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_role.role_desc
     *
     * @return the value of db_role.role_desc
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_role.role_desc
     *
     * @param roleDesc the value for db_role.role_desc
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_role.order_no
     *
     * @return the value of db_role.order_no
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_role.order_no
     *
     * @param orderNo the value for db_role.order_no
     *
     * @mbggenerated Sun Apr 12 23:45:07 CST 2020
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }
}