package com.yxb.cms.domain.vo;

public class DbRoleMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_role_menu.role_menu_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String roleMenuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_role_menu.fk_role_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String fkRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_role_menu.fk_menu_info_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String fkMenuInfoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_role_menu.role_menu_id
     *
     * @return the value of db_role_menu.role_menu_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getRoleMenuId() {
        return roleMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_role_menu.role_menu_id
     *
     * @param roleMenuId the value for db_role_menu.role_menu_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setRoleMenuId(String roleMenuId) {
        this.roleMenuId = roleMenuId == null ? null : roleMenuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_role_menu.fk_role_id
     *
     * @return the value of db_role_menu.fk_role_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getFkRoleId() {
        return fkRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_role_menu.fk_role_id
     *
     * @param fkRoleId the value for db_role_menu.fk_role_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setFkRoleId(String fkRoleId) {
        this.fkRoleId = fkRoleId == null ? null : fkRoleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_role_menu.fk_menu_info_id
     *
     * @return the value of db_role_menu.fk_menu_info_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getFkMenuInfoId() {
        return fkMenuInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_role_menu.fk_menu_info_id
     *
     * @param fkMenuInfoId the value for db_role_menu.fk_menu_info_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setFkMenuInfoId(String fkMenuInfoId) {
        this.fkMenuInfoId = fkMenuInfoId == null ? null : fkMenuInfoId.trim();
    }
}