package com.yxb.cms.domain.vo;

import java.util.Date;

public class DbSysLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_sys_log.log_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_sys_log.log_title
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String logTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_sys_log.log_type
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String logType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_sys_log.log_url
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String logUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_sys_log.log_method
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String logMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_sys_log.log_params
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String logParams;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_sys_log.log_exception
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String logException;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_sys_log.log_user_name
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String logUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_sys_log.log_ip
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String logIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_sys_log.log_ip_address
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String logIpAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_sys_log.log_start_time
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private Date logStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_sys_log.log_elapsed_time
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private Double logElapsedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_sys_log.log_id
     *
     * @return the value of db_sys_log.log_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_sys_log.log_id
     *
     * @param logId the value for db_sys_log.log_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setLogId(String logId) {
        this.logId = logId == null ? null : logId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_sys_log.log_title
     *
     * @return the value of db_sys_log.log_title
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getLogTitle() {
        return logTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_sys_log.log_title
     *
     * @param logTitle the value for db_sys_log.log_title
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setLogTitle(String logTitle) {
        this.logTitle = logTitle == null ? null : logTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_sys_log.log_type
     *
     * @return the value of db_sys_log.log_type
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_sys_log.log_type
     *
     * @param logType the value for db_sys_log.log_type
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setLogType(String logType) {
        this.logType = logType == null ? null : logType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_sys_log.log_url
     *
     * @return the value of db_sys_log.log_url
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getLogUrl() {
        return logUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_sys_log.log_url
     *
     * @param logUrl the value for db_sys_log.log_url
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setLogUrl(String logUrl) {
        this.logUrl = logUrl == null ? null : logUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_sys_log.log_method
     *
     * @return the value of db_sys_log.log_method
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getLogMethod() {
        return logMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_sys_log.log_method
     *
     * @param logMethod the value for db_sys_log.log_method
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setLogMethod(String logMethod) {
        this.logMethod = logMethod == null ? null : logMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_sys_log.log_params
     *
     * @return the value of db_sys_log.log_params
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getLogParams() {
        return logParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_sys_log.log_params
     *
     * @param logParams the value for db_sys_log.log_params
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setLogParams(String logParams) {
        this.logParams = logParams == null ? null : logParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_sys_log.log_exception
     *
     * @return the value of db_sys_log.log_exception
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getLogException() {
        return logException;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_sys_log.log_exception
     *
     * @param logException the value for db_sys_log.log_exception
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setLogException(String logException) {
        this.logException = logException == null ? null : logException.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_sys_log.log_user_name
     *
     * @return the value of db_sys_log.log_user_name
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getLogUserName() {
        return logUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_sys_log.log_user_name
     *
     * @param logUserName the value for db_sys_log.log_user_name
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setLogUserName(String logUserName) {
        this.logUserName = logUserName == null ? null : logUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_sys_log.log_ip
     *
     * @return the value of db_sys_log.log_ip
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getLogIp() {
        return logIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_sys_log.log_ip
     *
     * @param logIp the value for db_sys_log.log_ip
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setLogIp(String logIp) {
        this.logIp = logIp == null ? null : logIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_sys_log.log_ip_address
     *
     * @return the value of db_sys_log.log_ip_address
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getLogIpAddress() {
        return logIpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_sys_log.log_ip_address
     *
     * @param logIpAddress the value for db_sys_log.log_ip_address
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setLogIpAddress(String logIpAddress) {
        this.logIpAddress = logIpAddress == null ? null : logIpAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_sys_log.log_start_time
     *
     * @return the value of db_sys_log.log_start_time
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public Date getLogStartTime() {
        return logStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_sys_log.log_start_time
     *
     * @param logStartTime the value for db_sys_log.log_start_time
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setLogStartTime(Date logStartTime) {
        this.logStartTime = logStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_sys_log.log_elapsed_time
     *
     * @return the value of db_sys_log.log_elapsed_time
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public Double getLogElapsedTime() {
        return logElapsedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_sys_log.log_elapsed_time
     *
     * @param logElapsedTime the value for db_sys_log.log_elapsed_time
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setLogElapsedTime(Double logElapsedTime) {
        this.logElapsedTime = logElapsedTime;
    }
}