package com.yxb.cms.domain.vo;

public class DbTaskMember {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_task_member.task_member_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private String taskMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_task_member.fk_task_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private String fkTaskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_task_member.fk_member_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private String fkMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_task_member.mmember_name
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    private String mmemberName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_task_member.task_member_id
     *
     * @return the value of db_task_member.task_member_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public String getTaskMemberId() {
        return taskMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_task_member.task_member_id
     *
     * @param taskMemberId the value for db_task_member.task_member_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setTaskMemberId(String taskMemberId) {
        this.taskMemberId = taskMemberId == null ? null : taskMemberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_task_member.fk_task_id
     *
     * @return the value of db_task_member.fk_task_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public String getFkTaskId() {
        return fkTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_task_member.fk_task_id
     *
     * @param fkTaskId the value for db_task_member.fk_task_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setFkTaskId(String fkTaskId) {
        this.fkTaskId = fkTaskId == null ? null : fkTaskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_task_member.fk_member_id
     *
     * @return the value of db_task_member.fk_member_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public String getFkMemberId() {
        return fkMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_task_member.fk_member_id
     *
     * @param fkMemberId the value for db_task_member.fk_member_id
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setFkMemberId(String fkMemberId) {
        this.fkMemberId = fkMemberId == null ? null : fkMemberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_task_member.mmember_name
     *
     * @return the value of db_task_member.mmember_name
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public String getMmemberName() {
        return mmemberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_task_member.mmember_name
     *
     * @param mmemberName the value for db_task_member.mmember_name
     *
     * @mbggenerated Thu May 07 11:47:20 CST 2020
     */
    public void setMmemberName(String mmemberName) {
        this.mmemberName = mmemberName == null ? null : mmemberName.trim();
    }
}