package com.yxb.cms.domain.vo;

import java.util.Date;

public class DbUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_user.user_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_user.user_account
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String userAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_user.login_pwd
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String loginPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_user.user_name
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_user.user_status
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private Integer userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_user.user_type
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_user.creater_user_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String createrUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_user.creater_time
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private Date createrTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_user.modifier_user_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private String modifierUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_user.modifier_time
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    private Date modifierTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_user.user_id
     *
     * @return the value of db_user.user_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_user.user_id
     *
     * @param userId the value for db_user.user_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_user.user_account
     *
     * @return the value of db_user.user_account
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_user.user_account
     *
     * @param userAccount the value for db_user.user_account
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_user.login_pwd
     *
     * @return the value of db_user.login_pwd
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_user.login_pwd
     *
     * @param loginPwd the value for db_user.login_pwd
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_user.user_name
     *
     * @return the value of db_user.user_name
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_user.user_name
     *
     * @param userName the value for db_user.user_name
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_user.user_status
     *
     * @return the value of db_user.user_status
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_user.user_status
     *
     * @param userStatus the value for db_user.user_status
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_user.user_type
     *
     * @return the value of db_user.user_type
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_user.user_type
     *
     * @param userType the value for db_user.user_type
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_user.creater_user_id
     *
     * @return the value of db_user.creater_user_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getCreaterUserId() {
        return createrUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_user.creater_user_id
     *
     * @param createrUserId the value for db_user.creater_user_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setCreaterUserId(String createrUserId) {
        this.createrUserId = createrUserId == null ? null : createrUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_user.creater_time
     *
     * @return the value of db_user.creater_time
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public Date getCreaterTime() {
        return createrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_user.creater_time
     *
     * @param createrTime the value for db_user.creater_time
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setCreaterTime(Date createrTime) {
        this.createrTime = createrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_user.modifier_user_id
     *
     * @return the value of db_user.modifier_user_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public String getModifierUserId() {
        return modifierUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_user.modifier_user_id
     *
     * @param modifierUserId the value for db_user.modifier_user_id
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setModifierUserId(String modifierUserId) {
        this.modifierUserId = modifierUserId == null ? null : modifierUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_user.modifier_time
     *
     * @return the value of db_user.modifier_time
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public Date getModifierTime() {
        return modifierTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_user.modifier_time
     *
     * @param modifierTime the value for db_user.modifier_time
     *
     * @mbggenerated Thu Apr 09 18:03:43 CST 2020
     */
    public void setModifierTime(Date modifierTime) {
        this.modifierTime = modifierTime;
    }
}